// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShoppingApplication.Data;

#nullable disable

namespace OnlineShoppingApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260708103144_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineShoppingApplication.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OnlineShoppingApplication.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("OnlineShoppingApplication.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Description = "High-performance laptop with 16GB RAM and 512GB SSD",
                            Discount = 10,
                            Name = "Laptop",
                            Price = 75000m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Accessories",
                            Description = "Ergonomic wireless mouse with 2.4GHz connection",
                            Discount = 5,
                            Name = "Wireless Mouse",
                            Price = 1500m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 3,
                            Category = "Accessories",
                            Description = "Premium USB-C charging and data transfer cable",
                            Discount = 0,
                            Name = "USB-C Cable",
                            Price = 800m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 4,
                            Category = "Accessories",
                            Description = "RGB mechanical keyboard with Cherry MX switches",
                            Discount = 8,
                            Name = "Mechanical Keyboard",
                            Price = 8500m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 5,
                            Category = "Storage",
                            Description = "1TB portable SSD with USB-C connection, transfer speeds up to 1050MB/s",
                            Discount = 12,
                            Name = "Portable SSD",
                            Price = 12000m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 6,
                            Category = "Accessories",
                            Description = "7-port USB 3.0 hub with power adapter",
                            Discount = 5,
                            Name = "USB Hub",
                            Price = 2500m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 7,
                            Category = "Accessories",
                            Description = "Adjustable monitor stand with storage drawer",
                            Discount = 7,
                            Name = "Monitor Stand",
                            Price = 3500m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 8,
                            Category = "Electronics",
                            Description = "1080p HD webcam with built-in microphone",
                            Discount = 10,
                            Name = "Webcam",
                            Price = 4500m,
                            StockQuantity = 120
                        });
                });

            modelBuilder.Entity("OnlineShoppingApplication.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnlineShoppingApplication.Models.CartItem", b =>
                {
                    b.HasOne("OnlineShoppingApplication.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShoppingApplication.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShoppingApplication.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
